---

- name: Execute 'lynis audit system'
  ansible.builtin.shell: |
    set -o pipefail
    {{ lynis_root }}/lynis/lynis audit system | /usr/local/bin/ansi2html -a > /var/log/lynis.html
  args:
    executable: /bin/bash
  changed_when: false
  tags: molecule-idempotence-notest

- name: Fetch lynis results
  ansible.builtin.fetch:
    src: /var/log/{{ item }}
    dest: /tmp/{{ inventory_hostname }}-{{ item }}
    flat: yes
  loop:
    - lynis-report.dat
    - lynis.html
    - lynis.log
